### ISSUE TITLE
Feature: Expose SOCK5 Proxy

### ISSUE THREAD

**Issue by sfc9982** [aw1cks/openconnect#6]
Could you let the docker expose a SOCKS5 proxy?
I've tried to modify your code, but failed.
Thanks.

**Comment by aw1cks** [comment]
Hi there,

I'd recommend using something like `docker-compose` to put a proxy from another container in front of this one.

For example, you can do something like this:

```yaml
---

openconnect:
  image: aw1cks/openconnect:latest
 <configure openconnect container here>
```

...

```yaml
socks:
  # Using Squid as an example here,
  # any SOCKS-compatible proxy works fine
  # N.B. you probably need to configure Squid to do SOCKS - by default it will only do HTTP proxy
  image: ubuntu/squid:latest
  ports:
    - "3128:3128"
  restart: always
  # This will route the proxy's traffic through the `openconnect` service defined above
  network_mode: service:openconnect
```
